/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectSubjectIdRouteImport } from './routes/subject.$subjectId'
import { Route as NodeNodeIdRouteImport } from './routes/node.$nodeId'
import { Route as LessonNodeIdLevelIdRouteImport } from './routes/lesson.$nodeId.$levelId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectSubjectIdRoute = SubjectSubjectIdRouteImport.update({
  id: '/subject/$subjectId',
  path: '/subject/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const NodeNodeIdRoute = NodeNodeIdRouteImport.update({
  id: '/node/$nodeId',
  path: '/node/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonNodeIdLevelIdRoute = LessonNodeIdLevelIdRouteImport.update({
  id: '/lesson/$nodeId/$levelId',
  path: '/lesson/$nodeId/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/lesson/$nodeId/$levelId': typeof LessonNodeIdLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/lesson/$nodeId/$levelId': typeof LessonNodeIdLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
  '/subject/$subjectId': typeof SubjectSubjectIdRoute
  '/lesson/$nodeId/$levelId': typeof LessonNodeIdLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/review'
    | '/node/$nodeId'
    | '/subject/$subjectId'
    | '/lesson/$nodeId/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/review'
    | '/node/$nodeId'
    | '/subject/$subjectId'
    | '/lesson/$nodeId/$levelId'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/review'
    | '/node/$nodeId'
    | '/subject/$subjectId'
    | '/lesson/$nodeId/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ReviewRoute: typeof ReviewRoute
  NodeNodeIdRoute: typeof NodeNodeIdRoute
  SubjectSubjectIdRoute: typeof SubjectSubjectIdRoute
  LessonNodeIdLevelIdRoute: typeof LessonNodeIdLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$subjectId': {
      id: '/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof SubjectSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node/$nodeId': {
      id: '/node/$nodeId'
      path: '/node/$nodeId'
      fullPath: '/node/$nodeId'
      preLoaderRoute: typeof NodeNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$nodeId/$levelId': {
      id: '/lesson/$nodeId/$levelId'
      path: '/lesson/$nodeId/$levelId'
      fullPath: '/lesson/$nodeId/$levelId'
      preLoaderRoute: typeof LessonNodeIdLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  ReviewRoute: ReviewRoute,
  NodeNodeIdRoute: NodeNodeIdRoute,
  SubjectSubjectIdRoute: SubjectSubjectIdRoute,
  LessonNodeIdLevelIdRoute: LessonNodeIdLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
