/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodeNodeIdRouteImport } from './routes/node.$nodeId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LessonNodeIdLevelIdRouteImport } from './routes/lesson.$nodeId.$levelId'
import { Route as NodeNodeIdModuleModuleIndexRouteImport } from './routes/node.$nodeId_.module.$moduleIndex'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodeNodeIdRoute = NodeNodeIdRouteImport.update({
  id: '/node/$nodeId',
  path: '/node/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonNodeIdLevelIdRoute = LessonNodeIdLevelIdRouteImport.update({
  id: '/lesson/$nodeId/$levelId',
  path: '/lesson/$nodeId/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)
const NodeNodeIdModuleModuleIndexRoute =
  NodeNodeIdModuleModuleIndexRouteImport.update({
    id: '/node/$nodeId_/module/$moduleIndex',
    path: '/node/$nodeId/module/$moduleIndex',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
  '/lesson/$nodeId/$levelId': typeof LessonNodeIdLevelIdRoute
  '/node/$nodeId/module/$moduleIndex': typeof NodeNodeIdModuleModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
  '/lesson/$nodeId/$levelId': typeof LessonNodeIdLevelIdRoute
  '/node/$nodeId/module/$moduleIndex': typeof NodeNodeIdModuleModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/review': typeof ReviewRoute
  '/stats': typeof StatsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/node/$nodeId': typeof NodeNodeIdRoute
  '/lesson/$nodeId/$levelId': typeof LessonNodeIdLevelIdRoute
  '/node/$nodeId_/module/$moduleIndex': typeof NodeNodeIdModuleModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/leaderboard'
    | '/profile'
    | '/quiz'
    | '/review'
    | '/stats'
    | '/auth/callback'
    | '/node/$nodeId'
    | '/lesson/$nodeId/$levelId'
    | '/node/$nodeId/module/$moduleIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/leaderboard'
    | '/profile'
    | '/quiz'
    | '/review'
    | '/stats'
    | '/auth/callback'
    | '/node/$nodeId'
    | '/lesson/$nodeId/$levelId'
    | '/node/$nodeId/module/$moduleIndex'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/leaderboard'
    | '/profile'
    | '/quiz'
    | '/review'
    | '/stats'
    | '/auth/callback'
    | '/node/$nodeId'
    | '/lesson/$nodeId/$levelId'
    | '/node/$nodeId_/module/$moduleIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  ReviewRoute: typeof ReviewRoute
  StatsRoute: typeof StatsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  NodeNodeIdRoute: typeof NodeNodeIdRoute
  LessonNodeIdLevelIdRoute: typeof LessonNodeIdLevelIdRoute
  NodeNodeIdModuleModuleIndexRoute: typeof NodeNodeIdModuleModuleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node/$nodeId': {
      id: '/node/$nodeId'
      path: '/node/$nodeId'
      fullPath: '/node/$nodeId'
      preLoaderRoute: typeof NodeNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$nodeId/$levelId': {
      id: '/lesson/$nodeId/$levelId'
      path: '/lesson/$nodeId/$levelId'
      fullPath: '/lesson/$nodeId/$levelId'
      preLoaderRoute: typeof LessonNodeIdLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/node/$nodeId_/module/$moduleIndex': {
      id: '/node/$nodeId_/module/$moduleIndex'
      path: '/node/$nodeId/module/$moduleIndex'
      fullPath: '/node/$nodeId/module/$moduleIndex'
      preLoaderRoute: typeof NodeNodeIdModuleModuleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  LeaderboardRoute: LeaderboardRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  ReviewRoute: ReviewRoute,
  StatsRoute: StatsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  NodeNodeIdRoute: NodeNodeIdRoute,
  LessonNodeIdLevelIdRoute: LessonNodeIdLevelIdRoute,
  NodeNodeIdModuleModuleIndexRoute: NodeNodeIdModuleModuleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
